name: ReasonWL
version: 1.1
api: 1.12.0
main: reasonWL\Main
author: CreeperFace
description: plugin for set custom reason for whitelist

commands:
    rwl:
        description: "whitelist command"
        permission: rwl

permissions:
    rwl:
        description: "reasonWL plugin"
        default: op
        children:
            rwl.add:
                description: "add player to the whitelist"
                default: op
            rwl.remove:
                description: "remove player from whitelist"
                default: op
            rwl.access:
                description: "allows group to join the server when it is whitelisted"
                default: op
                
